"""reconcile schema metadata

Revision ID: 0004_schema_reconciliation
Revises: 0003_phase6_ai
Create Date: 2026-07-15 22:31:47.505556
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0004_schema_reconciliation"
down_revision: str | None = "0003_phase6_ai"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("rows_extracted", sa.Integer(), nullable=True),
        sa.Column("rows_transformed", sa.Integer(), nullable=True),
        sa.Column("rows_loaded", sa.Integer(), nullable=True),
        sa.Column("duplicates_removed", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_runs_run_id"), ["run_id"], unique=True)

    op.create_table(
        "sales",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=True),
        sa.Column("ship_date", sa.Date(), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("segment", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("sub_category", sa.String(length=100), nullable=True),
        sa.Column("product_name", sa.String(length=500), nullable=True),
        sa.Column("sales", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("discount", sa.Float(), nullable=False),
        sa.Column("profit", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.create_index("idx_order_date_region", ["order_date", "region"], unique=False)
        batch_op.create_index("idx_region_category", ["region", "category"], unique=False)
        batch_op.create_index(batch_op.f("ix_sales_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_sales_customer_name"), ["customer_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_sales_order_date"), ["order_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_sales_order_id"), ["order_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_sales_region"), ["region"], unique=False)

    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_anomaly_alerts", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "resolved_by",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_audit_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
        )

    with op.batch_alter_table("ai_documents", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_forecasts", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_insights", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_kpi_recommendations", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_messages", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "conversation_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
        )

    with op.batch_alter_table("ai_plugins", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_prompt_templates", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_provider_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_report_generations", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_usage_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_workflow_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "workflow_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
        )

    with op.batch_alter_table("ai_workflows", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=True,
        )

    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("branches", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("etl_data_profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "row_count", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "column_count", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("etl_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "trigger_type",
            existing_type=sa.VARCHAR(length=30),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "rows_extracted",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "rows_transformed",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "rows_loaded", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "rows_rejected",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_pipeline_steps", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "retry_count", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("etl_pipeline_versions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("etl_pipelines", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "current_version",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_quality_reports", schema=None) as batch_op:
        batch_op.alter_column(
            "overall_score",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checks_passed",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checks_failed",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checks_warning",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_schedules", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("etl_transformations", schema=None) as batch_op:
        batch_op.alter_column(
            "is_builtin", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("login_history", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "success", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("password_resets", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.drop_constraint("uq_role_permission", type_="unique")

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_system", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("security_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "severity",
            existing_type=sa.VARCHAR(length=20),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("system_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    with op.batch_alter_table("user_activity", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.drop_constraint("uq_user_role", type_="unique")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BIGINT(),
            type_=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            existing_nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "language",
            existing_type=sa.VARCHAR(length=10),
            server_default=None,
            existing_nullable=True,
        )
        batch_op.alter_column(
            "timezone",
            existing_type=sa.VARCHAR(length=50),
            server_default=None,
            existing_nullable=True,
        )
        batch_op.alter_column(
            "is_active", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "is_deleted", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )
        batch_op.alter_column(
            "failed_login_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "failed_login_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "timezone",
            existing_type=sa.VARCHAR(length=50),
            server_default=sa.text("'UTC'"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "language",
            existing_type=sa.VARCHAR(length=10),
            server_default=sa.text("'en'"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_user_role", ["user_id", "role_id"])
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("user_activity", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("system_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("security_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "severity",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'info'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_system",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_role_permission", ["role_id", "permission_id"])
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("password_resets", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("login_history", schema=None) as batch_op:
        batch_op.alter_column(
            "success",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("etl_transformations", schema=None) as batch_op:
        batch_op.alter_column(
            "is_builtin",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_schedules", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_quality_reports", schema=None) as batch_op:
        batch_op.alter_column(
            "checks_warning",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checks_failed",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "checks_passed",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "overall_score",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_pipelines", schema=None) as batch_op:
        batch_op.alter_column(
            "current_version",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'active'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_pipeline_versions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_pipeline_steps", schema=None) as batch_op:
        batch_op.alter_column(
            "retry_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'pending'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "rows_rejected",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "rows_loaded",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "rows_transformed",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "rows_extracted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "trigger_type",
            existing_type=sa.VARCHAR(length=30),
            server_default=sa.text("'manual'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=20),
            server_default=sa.text("'queued'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("etl_data_profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "column_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "row_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("branches", schema=None) as batch_op:
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("api_tokens", schema=None) as batch_op:
        batch_op.alter_column(
            "is_deleted",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_workflows", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_workflow_runs", schema=None) as batch_op:
        batch_op.alter_column(
            "workflow_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_usage_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_report_generations", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_provider_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_prompt_templates", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_plugins", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_messages", schema=None) as batch_op:
        batch_op.alter_column(
            "conversation_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_kpi_recommendations", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_insights", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_forecasts", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_documents", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_audit_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("ai_anomaly_alerts", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "resolved_by",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("activity_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            type_=sa.BIGINT(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sales_region"))
        batch_op.drop_index(batch_op.f("ix_sales_order_id"))
        batch_op.drop_index(batch_op.f("ix_sales_order_date"))
        batch_op.drop_index(batch_op.f("ix_sales_customer_name"))
        batch_op.drop_index(batch_op.f("ix_sales_category"))
        batch_op.drop_index("idx_region_category")
        batch_op.drop_index("idx_order_date_region")

    op.drop_table("sales")
    with op.batch_alter_table("pipeline_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_runs_run_id"))

    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
