"""add analytics domain

Revision ID: 3ab0de986206
Revises: 84a96d4ff144
Create Date: 2026-07-16 00:46:32.918340
"""

from collections.abc import Sequence

revision: str = "3ab0de986206"
down_revision: str | None = "84a96d4ff144"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
