"""add analytics domain

Revision ID: 3ab0de986206
Revises: 84a96d4ff144
Create Date: 2026-07-16 00:46:32.918340
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ab0de986206'
down_revision: Union[str, None] = '84a96d4ff144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
