"""add organization team management

Revision ID: 84a96d4ff144
Revises: 0004_schema_reconciliation
Create Date: 2026-07-15 23:40:42.955732
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "84a96d4ff144"
down_revision: str | None = "0004_schema_reconciliation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_members",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_members_team_id"), ["team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_team_members_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("website_url", sa.String(length=500), nullable=True))
        batch_op.add_column(
            sa.Column("business_registration_number", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("timezone", sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column("date_format", sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column("locale", sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column("branding", sa.JSON(), nullable=True))

    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.add_column(sa.Column("settings", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("teams", schema=None) as batch_op:
        batch_op.drop_column("settings")

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_column("branding")
        batch_op.drop_column("locale")
        batch_op.drop_column("date_format")
        batch_op.drop_column("timezone")
        batch_op.drop_column("business_registration_number")
        batch_op.drop_column("website_url")

    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_team_members_team_id"))

    op.drop_table("team_members")
    # ### end Alembic commands ###
