"""Nigeria Country Profile.

Nigeria-specific data including:
  - 36 states + FCT
  - NGN currency (Naira)
  - Local industries (oil, agriculture, telecommunications)
  - Education, healthcare, agriculture structures
"""

from __future__ import annotations

from africa_intelligence.base import (
    AgricultureStructure,
    CountryProfile,
    CurrencyInfo,
    EducationStructure,
    HealthcareStructure,
    IndustryInfo,
    RegionInfo,
)

NIGERIA_PROFILE = CountryProfile(
    name="Nigeria",
    code="NG",
    dialing_code="234",
    capital="Abuja",
    official_languages=["English"],
    currency=CurrencyInfo(
        code="NGN",
        name="Naira",
        symbol="â‚¦",
        subunit="Kobo",
        subunit_symbol="k",
        decimal_places=2,
        exchange_rate_to_usd=0.00067,
    ),
    regions=[
        RegionInfo(
            name="Lagos",
            code="LA",
            capital="Ikeja",
            population=15388999,
            area_km2=3577,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Abia",
            code="AB",
            capital="Umuahia",
            population=3825760,
            area_km2=6320,
            languages=["English", "Igbo"],
        ),
        RegionInfo(
            name="Adamawa",
            code="AD",
            capital="Yola",
            population=4258933,
            area_km2=36917,
            languages=["English", "Fulfulde"],
        ),
        RegionInfo(
            name="Akwa Ibom",
            code="AK",
            capital="Uyo",
            population=5481257,
            area_km2=7081,
            languages=["English", "Ibibio"],
        ),
        RegionInfo(
            name="Anambra",
            code="AN",
            capital="Awka",
            population=5527809,
            area_km2=4844,
            languages=["English", "Igbo"],
        ),
        RegionInfo(
            name="Bauchi",
            code="BA",
            capital="Bauchi",
            population=6553658,
            area_km2=45837,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Bayelsa",
            code="BY",
            capital="Yenagoa",
            population=2261856,
            area_km2=10773,
            languages=["English", "Ijaw"],
        ),
        RegionInfo(
            name="Benue",
            code="BN",
            capital="Makurdi",
            population=5860938,
            area_km2=34059,
            languages=["English", "Tiv"],
        ),
        RegionInfo(
            name="Borno",
            code="BO",
            capital="Maiduguri",
            population=5831567,
            area_km2=70898,
            languages=["English", "Kanuri"],
        ),
        RegionInfo(
            name="Cross River",
            code="CR",
            capital="Calabar",
            population=3967285,
            area_km2=20156,
            languages=["English", "Efik"],
        ),
        RegionInfo(
            name="Delta",
            code="DE",
            capital="Asaba",
            population=6096871,
            area_km2=17698,
            languages=["English", "Urhobo"],
        ),
        RegionInfo(
            name="Ebonyi",
            code="EB",
            capital="Abakaliki",
            population=2941273,
            area_km2=5670,
            languages=["English", "Igbo"],
        ),
        RegionInfo(
            name="Edo",
            code="ED",
            capital="Benin City",
            population=4777602,
            area_km2=17802,
            languages=["English", "Edo"],
        ),
        RegionInfo(
            name="Ekiti",
            code="EK",
            capital="Ado-Ekiti",
            population=3270987,
            area_km2=6353,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Enugu",
            code="EN",
            capital="Enugu",
            population=4261878,
            area_km2=7161,
            languages=["English", "Igbo"],
        ),
        RegionInfo(
            name="FCT (Abuja)",
            code="FC",
            capital="Abuja",
            population=3500000,
            area_km2=7315,
            languages=["English", "Gbagyi"],
        ),
        RegionInfo(
            name="Gombe",
            code="GO",
            capital="Gombe",
            population=3299430,
            area_km2=18768,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Imo",
            code="IM",
            capital="Owerri",
            population=5220728,
            area_km2=5530,
            languages=["English", "Igbo"],
        ),
        RegionInfo(
            name="Jigawa",
            code="JG",
            capital="Dutse",
            population=6169105,
            area_km2=22410,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Kaduna",
            code="KD",
            capital="Kaduna",
            population=8252366,
            area_km2=46054,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Kano",
            code="KN",
            capital="Kano",
            population=13499120,
            area_km2=20760,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Katsina",
            code="KT",
            capital="Katsina",
            population=7934202,
            area_km2=24228,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Kebbi",
            code="KB",
            capital="Birnin Kebbi",
            population=4735925,
            area_km2=36808,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Kogi",
            code="KG",
            capital="Lokoja",
            population=4473384,
            area_km2=29833,
            languages=["English", "Igala"],
        ),
        RegionInfo(
            name="Kwara",
            code="KW",
            capital="Ilorin",
            population=3192843,
            area_km2=36825,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Nasarawa",
            code="NS",
            capital="Lafia",
            population=2523195,
            area_km2=27117,
            languages=["English", "Eggon"],
        ),
        RegionInfo(
            name="Niger",
            code="NG",
            capital="Minna",
            population=5902365,
            area_km2=76363,
            languages=["English", "Nupe"],
        ),
        RegionInfo(
            name="Ogun",
            code="OG",
            capital="Abeokuta",
            population=5217716,
            area_km2=16762,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Ondo",
            code="OD",
            capital="Akure",
            population=4790195,
            area_km2=15700,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Osun",
            code="OS",
            capital="Osogbo",
            population=4168769,
            area_km2=9251,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Oyo",
            code="OY",
            capital="Ibadan",
            population=7812200,
            area_km2=28454,
            languages=["English", "Yoruba"],
        ),
        RegionInfo(
            name="Plateau",
            code="PL",
            capital="Jos",
            population=4757982,
            area_km2=30913,
            languages=["English", "Berom"],
        ),
        RegionInfo(
            name="Rivers",
            code="RV",
            capital="Port Harcourt",
            population=7286937,
            area_km2=11291,
            languages=["English", "Ikwerre"],
        ),
        RegionInfo(
            name="Sokoto",
            code="SO",
            capital="Sokoto",
            population=4841920,
            area_km2=25973,
            languages=["English", "Hausa"],
        ),
        RegionInfo(
            name="Taraba",
            code="TR",
            capital="Jalingo",
            population=3122466,
            area_km2=54048,
            languages=["English", "Jukun"],
        ),
        RegionInfo(
            name="Yobe",
            code="YO",
            capital="Damaturu",
            population=3324570,
            area_km2=45502,
            languages=["English", "Kanuri"],
        ),
        RegionInfo(
            name="Zamfara",
            code="ZM",
            capital="Gusau",
            population=4119327,
            area_km2=39762,
            languages=["English", "Hausa"],
        ),
    ],
    industries=[
        IndustryInfo(
            name="Oil and Gas",
            sector="Energy",
            description="Nigeria is Africa's largest oil producer.",
            key_products=["crude oil", "natural gas", "LNG", "petroleum"],
            regions=["Rivers", "Delta", "Bayelsa", "Akwa Ibom"],
            contribution_to_gdp=8.0,
        ),
        IndustryInfo(
            name="Agriculture",
            sector="Agriculture",
            description="Largest employer, producing crops for domestic and export markets.",
            key_products=["cassava", "yam", "maize", "rice", "cocoa", "palm oil", "groundnut"],
            regions=["Benue", "Kano", "Kaduna", "Oyo", "Plateau"],
            contribution_to_gdp=23.0,
        ),
        IndustryInfo(
            name="Telecommunications",
            sector="Services",
            description="Fast-growing telecom sector with mobile money and fintech.",
            key_products=["mobile services", "data", "fintech", "mobile money"],
            regions=["Lagos", "Abuja"],
            contribution_to_gdp=12.0,
        ),
        IndustryInfo(
            name="Nollywood (Film)",
            sector="Entertainment",
            description="Second-largest film industry in the world by output.",
            key_products=["films", "movies", "TV shows", "music"],
            regions=["Lagos"],
            contribution_to_gdp=2.0,
        ),
        IndustryInfo(
            name="Banking and Finance",
            sector="Financial Services",
            description="Major financial hub in West Africa.",
            key_products=["banking", "insurance", "fintech", "capital markets"],
            regions=["Lagos", "Abuja"],
            contribution_to_gdp=6.0,
        ),
    ],
    education=EducationStructure(
        levels=[
            {"name": "Primary School", "duration": "6 years", "ages": "6-11"},
            {"name": "Junior Secondary School (JSS)", "duration": "3 years", "ages": "12-14"},
            {"name": "Senior Secondary School (SSS)", "duration": "3 years", "ages": "15-17"},
            {"name": "Tertiary (University)", "duration": "4-6 years", "ages": "18+"},
            {"name": "Tertiary (Polytechnic)", "duration": "2-4 years", "ages": "18+"},
        ],
        grading_scales={
            "SSS": [
                {"grade": "A1", "score": "80-100", "interpretation": "Excellent"},
                {"grade": "B2", "score": "70-79", "interpretation": "Very Good"},
                {"grade": "B3", "score": "65-69", "interpretation": "Good"},
                {"grade": "C4", "score": "60-64", "interpretation": "Credit"},
                {"grade": "C5", "score": "55-59", "interpretation": "Credit"},
                {"grade": "C6", "score": "50-54", "interpretation": "Credit"},
                {"grade": "D7", "score": "45-49", "interpretation": "Pass"},
                {"grade": "E8", "score": "40-44", "interpretation": "Pass"},
                {"grade": "F9", "score": "0-39", "interpretation": "Fail"},
            ],
        },
        academic_year="September to July (3 terms)",
        school_types=["Public", "Private", "Mission", "Federal"],
        examination_bodies=["WAEC (WASSCE)", "NECO", "JAMB", "NABTEB"],
        notable_institutions=[
            "University of Ibadan (UI)",
            "University of Lagos (UNILAG)",
            "Ahmadu Bello University (ABU)",
            "Obafemi Awolowo University (OAU)",
            "University of Nigeria, Nsukka (UNN)",
            "Covenant University",
        ],
    ),
    healthcare=HealthcareStructure(
        tiers=[
            {
                "name": "Primary Health Centre",
                "level": "Primary",
                "description": "Ward-level primary care",
            },
            {
                "name": "General Hospital",
                "level": "Secondary",
                "description": "Local government level",
            },
            {
                "name": "Federal Medical Centre / Teaching Hospital",
                "level": "Tertiary",
                "description": "State/Federal referral",
            },
        ],
        insurance_schemes=[
            {
                "name": "National Health Insurance Scheme (NHIS)",
                "type": "Public",
                "coverage": "Formal sector + informal",
            },
            {"name": "Private Health Insurance (HMOs)", "type": "Private", "coverage": "Corporate"},
        ],
        facility_types=[
            "Primary Health Centre",
            "General Hospital",
            "Teaching Hospital",
            "Federal Medical Centre",
            "Private Hospital",
            "Maternity Home",
        ],
        major_diseases=[
            "Malaria",
            "HIV/AIDS",
            "Tuberculosis",
            "Lassa Fever",
            "Cholera",
            "Yellow Fever",
        ],
        regulatory_bodies=[
            "Nigeria Centre for Disease Control (NCDC)",
            "Medical and Dental Council of Nigeria (MDCN)",
            "NAFDAC",
        ],
        doctor_to_patient_ratio="1:5,000 (approximate)",
    ),
    agriculture=AgricultureStructure(
        major_crops=[
            {
                "name": "Cassava",
                "season": "Year-round",
                "regions": ["Benue", "Cross River", "Delta"],
                "export": False,
            },
            {
                "name": "Yam",
                "season": "August-November",
                "regions": ["Benue", "Nasarawa", "Taraba"],
                "export": False,
            },
            {
                "name": "Rice",
                "season": "May-October",
                "regions": ["Kebbi", "Kano", "Niger"],
                "export": False,
            },
            {
                "name": "Cocoa",
                "season": "October-September",
                "regions": ["Oyo", "Ondo", "Cross River"],
                "export": True,
            },
            {
                "name": "Palm Oil",
                "season": "Year-round",
                "regions": ["Delta", "Edo", "Cross River"],
                "export": True,
            },
            {
                "name": "Groundnut",
                "season": "November-March",
                "regions": ["Kano", "Katsina", "Jigawa"],
                "export": True,
            },
        ],
        farming_systems=[
            "Smallholder farming",
            "Commercial plantations",
            "Pastoralism",
            "Irrigation farming",
        ],
        growing_seasons=[
            {"name": "Rainy Season (South)", "period": "March-October", "rainfall": "Heavy"},
            {"name": "Rainy Season (North)", "period": "June-September", "rainfall": "Moderate"},
            {"name": "Dry Season", "period": "November-March", "rainfall": "Harmattan"},
        ],
        livestock=["Cattle", "Sheep", "Goats", "Poultry", "Pigs"],
        export_crops=["Cocoa", "Palm oil", "Groundnut", "Rubber", "Cashew"],
        challenges=[
            "Insecurity in farming regions",
            "Climate change",
            "Limited irrigation",
            "Post-harvest losses",
        ],
    ),
    national_holidays=[
        {"name": "New Year's Day", "date": "January 1"},
        {"name": "Independence Day", "date": "October 1"},
        {"name": "Democracy Day", "date": "June 12"},
        {"name": "Christmas Day", "date": "December 25"},
        {"name": "Boxing Day", "date": "December 26"},
        {"name": "Eid al-Fitr", "date": "Variable"},
        {"name": "Eid al-Adha", "date": "Variable"},
        {"name": "Good Friday", "date": "Variable"},
        {"name": "Easter Monday", "date": "Variable"},
        {"name": "Workers' Day", "date": "May 1"},
    ],
    demographics={
        "population": 223000000,
        "life_expectancy": 53.0,
        "literacy_rate": 62.0,
        "urban_population_pct": 53.0,
        "major_ethnic_groups": ["Hausa", "Yoruba", "Igbo", "Fulani", "Tiv", "Ijaw"],
        "major_religions": ["Christianity", "Islam", "Traditional"],
    },
)
